### ISSUE TITLE
[Suggestions] Suggestions for April

### ISSUE THREAD

**Issue by quasixi** [quasixi/RPG-Maker-MV#15]
_Every month I will open a discussion where you may recommend plugins, addons, apps, or tutorials that you want me to create. This discussion will be closed in the middle of the month. A poll will be created for the second half of the month filled with approved requests. At the end of the month I will pick the top 1 or more requests and create them in the following month._

**Requests Submission deadline:** March 19, 2016 around noon.

Feel free to request anything. Anything that I think can be created under a month will be approved.

_* If you are a Patreon supporter of Rank 2 or higher, send me a message on Patreon with your github user name so I can confirm who you are. Patreon suggestions will have a +1 to their suggestion when voting. When there is a tie and one is a Patreon suggestion, the Patreon suggestion will take priority._

**Comment by Ronivan2** [comment]
I would recommend the creation of a simple plugin which allows the user to choose the numbers of items they could carry. Not only limiting the amount of items, but let the user choose the number for each item in inventory based on item comment. Lets say I want to limit #1 Potion to a max of 30, and then the next is a #2 High Potion to a max of 20, and then lets say item Elixir to a max of 5. The plugin would allow user to directly choose the max limit for each item individually. I've seem some plugins that limites the number of items, but none would let the user specify the amount for each item individually. 
Such plugin would make the player think well before using multiple times healing itens or other key items.

**Comment by quasixi** [comment]
True, I'll accept that suggestion.

**Comment by Kyuukon** [comment]
Hmm. I might as well ask since I'm in need for it.

Do you know Yanfly Message Core? Here: http://yanfly.moe/2015/10/10/yep-2-message-core/
It's a nice plugin that extends the limited default message system capabilities. However, it lacks certain features I'm pretty sure most would like to see. Some of them include: animated faces, busts, dialog bubbles and even multiple messages boxes. Do you think you could write something compatible and with those requirements in a month? Messages are very important for any game :3!

Here is an example taken from Fogomax's plugin (which isn't complete) that may help envision: http://i.imgur.com/PBwENTR.gif

Thanks. Looking forward whatever stuff you make :D

**Comment by quasixi** [comment]
@Kyuukon Yeah that's a bit bigger and I don't really like to work with other plugins. So sadly I will have to deny since that will probably take most of the month or more.

**Comment by Kyuukon** [comment]
@quasixi I see...
Hmm, what about this one then: A plugin that allows you to use regions to show/hide areas by a fog of war.
Hopefully, you get the idea but basically, it'd be a command that says: "hide_region(10, 40)" and then all map and events in region 10 would be covered by black in fade out of 40 seconds. Same with "show_region(10,40)" but with fade in. Or something like that. You the expert here xD!

**Comment by quasixi** [comment]
Sure that would be fine. Though there already is a fog of war plugin in MV it just doesn't have any fade in / out effects.
https://www.youtube.com/watch?v=_7cSO5snG-I

**Comment by Kyuukon** [comment]
@quasixi Oh. I didn't know x)! Well, I will leave that up to you then. The fade effect would be very neat :3

**Comment by quasixi** [comment]
You can always ask him to implement, should be pretty simple. I don't really like to recreate plugins cause it seems rude for me lol.

**Comment by quasixi** [comment]
Closing, there will be no poll as only 1 recommendation got accepted.
